### ISSUE TITLE
Deploy failing 

### ISSUE THREAD

**Issue by volga629** [paralin/openshift-under-kubernetes#6]
Hello Everyone,
Deploy function failing 
Tool was installed with pip

````
 openshift-under-kubernetes --config .kube/config_master deploy  --no-load-balancer --persistent-volume openshift-clst-1-pv
Loading kube config...
[note] we are in insecure mode, disabling warnings
Checking connectivity...
Currently there are 6 namespaces in the cluster.
Everything looks good, proceeding.
()
Collecting some initial cluster info...
list index out of range
It looks like we do have the openshift-origin namespace, and do not have a working ReplicationController.
Currently I do not consider this a complete OpenShift deployment.
()
The namespaces 'openshift' and/or 'openshift-origin' exist, this indicates a potentially existing/broken install.
Really consider the decision you're about to make.
Do you want to clear the existing installation? [y/N]: y
Deleting openshift-origin namespace...
Preparing to execute deploy...
Deploy temp dir: /tmp/tmp3GQ3nC
Cleaning up old openshift-deploy namespace.
Deleting openshift-deploy namespace...
Waiting for openshift-deploy to terminate...
Creating openshift-deploy namespace...
Checking for persistentvolume openshift-clst-1-pv...
Creating openshift-origin namespace...
Will use node port type service.
Creating 'openshift' service...
External OpenShift IP: nodes (node port)
Internal OpenShift IP: 10.111.152.134
Creating create-config-script secret...
Creating kubeconfig secret...
Generating openshift config via cluster...
Creating config generation pod...
Waiting for generate-config pod to finish...
Checking logs...
Retreived config bundle successfully.
Traceback (most recent call last):
  File "/usr/bin/openshift-under-kubernetes", line 11, in <module>
    load_entry_point('openshift-under-kubernetes==1.2.9', 'console_scripts', 'openshift-under-kubernetes')()
  File "/usr/lib/python2.7/site-packages/openshift_under_kubernetes/cli.py", line 561, in main
    cli()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openshift_under_kubernetes/cli.py", line 186, in deploy
    with open(server_key, 'r') as fs:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by alanconway** [comment]
I have the same issue - can you clarify which key is required for the --server-key paramter? Is it a private or public key? In comments on #3 you mention "serviceaccount.key", so I guess it's associated with a service account, but I'm not sure which one.

I built my cluster with `kubeadm init`, and there's nothing in the srv directory. I have the following .key files (that I know of) on master, none is obviously related to service accounts:

ssh root@master find /etc/kubernetes -name '*.key'
/etc/kubernetes/pki/etcd/peer.key
/etc/kubernetes/pki/etcd/server.key
/etc/kubernetes/pki/etcd/ca.key
/etc/kubernetes/pki/etcd/healthcheck-client.key
/etc/kubernetes/pki/apiserver-kubelet-client.key
/etc/kubernetes/pki/apiserver.key
/etc/kubernetes/pki/front-proxy-ca.key
/etc/kubernetes/pki/ca.key
/etc/kubernetes/pki/sa.key
/etc/kubernetes/pki/front-proxy-client.key
/etc/kubernetes/pki/apiserver-etcd-client.key

Thanks for your help!

**Comment by alanconway** [comment]
I tried /etc/kubernetes/pki/etcd/server.key (which is a private key) and I get further but the process hangs, I'm not sure if that's because its the wrong key or some other problem in my cluster (this is my first time deploying anything persistent so it is very possible the fault lies elsewhere)

```
 openshift-under-kubernetes --context kubernetes-admin@kubernetes deploy --load-balancer --create-volume --server-key tmp/server.key 
Loading kube config...
[note] we are in insecure mode, disabling warnings
Checking connectivity...
Currently there are 4 namespaces in the cluster.
Everything looks good, proceeding.
()
Collecting some initial cluster info...
list index out of range
It looks like we do not have the openshift-origin namespace, and do not have a working ReplicationController.
Currently I do not consider this a complete OpenShift deployment.
()
Preparing to execute deploy...
Deploy temp dir: /tmp/tmpBEJ4II
Creating openshift-deploy namespace...
Creating openshift-origin namespace...
Will use load balancer type service.
Creating 'openshift' service...
Waiting for service load balancer IP to be allocated...
External OpenShift IP: 192.168.1.150
Internal OpenShift IP: 10.102.227.145
Creating create-config-script secret...
Creating kubeconfig secret...
Generating openshift config via cluster...
Creating config generation pod...
Waiting for generate-config pod to finish...
Checking logs...
Retreived config bundle successfully.
/home/aconway/.local/lib/python2.7/site-packages/openshift_under_kubernetes/cli.py:182: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  conf = yaml.load(f)
Generated updated master-config.yaml.
Do you want to edit master-config.yaml? [y/N]: N
Creating openshift-config secret...
Creating etcd service...
Creating etcd controller...
Waiting for etcd pod to be created...
Waiting for etcd-f977m pod to start...

```
